# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from visionai.core.infer_proto import infer_pb2 as visionai_dot_infer_dot_v1_dot_infer__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = False

if False and _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in visionai/infer/v1/infer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InferServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Live = channel.unary_unary(
                '/visionai.infer.v1.InferService/Live',
                request_serializer=visionai_dot_infer_dot_v1_dot_infer__pb2.LiveRequest.SerializeToString,
                response_deserializer=visionai_dot_infer_dot_v1_dot_infer__pb2.LiveResponse.FromString,
                _registered_method=True)
        self.Ready = channel.unary_unary(
                '/visionai.infer.v1.InferService/Ready',
                request_serializer=visionai_dot_infer_dot_v1_dot_infer__pb2.ReadyRequest.SerializeToString,
                response_deserializer=visionai_dot_infer_dot_v1_dot_infer__pb2.ReadyResponse.FromString,
                _registered_method=True)
        self.ListModels = channel.unary_unary(
                '/visionai.infer.v1.InferService/ListModels',
                request_serializer=visionai_dot_infer_dot_v1_dot_infer__pb2.ListModelsRequest.SerializeToString,
                response_deserializer=visionai_dot_infer_dot_v1_dot_infer__pb2.ListModelsResponse.FromString,
                _registered_method=True)
        self.LoadModel = channel.unary_unary(
                '/visionai.infer.v1.InferService/LoadModel',
                request_serializer=visionai_dot_infer_dot_v1_dot_infer__pb2.LoadModelRequest.SerializeToString,
                response_deserializer=visionai_dot_infer_dot_v1_dot_infer__pb2.LoadModelResponse.FromString,
                _registered_method=True)
        self.UnloadModel = channel.unary_unary(
                '/visionai.infer.v1.InferService/UnloadModel',
                request_serializer=visionai_dot_infer_dot_v1_dot_infer__pb2.UnloadModelRequest.SerializeToString,
                response_deserializer=visionai_dot_infer_dot_v1_dot_infer__pb2.UnloadModelResponse.FromString,
                _registered_method=True)
        self.OpenSession = channel.unary_unary(
                '/visionai.infer.v1.InferService/OpenSession',
                request_serializer=visionai_dot_infer_dot_v1_dot_infer__pb2.OpenSessionRequest.SerializeToString,
                response_deserializer=visionai_dot_infer_dot_v1_dot_infer__pb2.OpenSessionResponse.FromString,
                _registered_method=True)
        self.UpdateSession = channel.unary_unary(
                '/visionai.infer.v1.InferService/UpdateSession',
                request_serializer=visionai_dot_infer_dot_v1_dot_infer__pb2.UpdateSessionRequest.SerializeToString,
                response_deserializer=visionai_dot_infer_dot_v1_dot_infer__pb2.UpdateSessionResponse.FromString,
                _registered_method=True)
        self.CloseSession = channel.unary_unary(
                '/visionai.infer.v1.InferService/CloseSession',
                request_serializer=visionai_dot_infer_dot_v1_dot_infer__pb2.CloseSessionRequest.SerializeToString,
                response_deserializer=visionai_dot_infer_dot_v1_dot_infer__pb2.CloseSessionResponse.FromString,
                _registered_method=True)
        self.Infer = channel.unary_unary(
                '/visionai.infer.v1.InferService/Infer',
                request_serializer=visionai_dot_infer_dot_v1_dot_infer__pb2.InferRequest.SerializeToString,
                response_deserializer=visionai_dot_infer_dot_v1_dot_infer__pb2.InferResponse.FromString,
                _registered_method=True)


class InferServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Live(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ready(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListModels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnloadModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpenSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Infer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InferServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Live': grpc.unary_unary_rpc_method_handler(
                    servicer.Live,
                    request_deserializer=visionai_dot_infer_dot_v1_dot_infer__pb2.LiveRequest.FromString,
                    response_serializer=visionai_dot_infer_dot_v1_dot_infer__pb2.LiveResponse.SerializeToString,
            ),
            'Ready': grpc.unary_unary_rpc_method_handler(
                    servicer.Ready,
                    request_deserializer=visionai_dot_infer_dot_v1_dot_infer__pb2.ReadyRequest.FromString,
                    response_serializer=visionai_dot_infer_dot_v1_dot_infer__pb2.ReadyResponse.SerializeToString,
            ),
            'ListModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModels,
                    request_deserializer=visionai_dot_infer_dot_v1_dot_infer__pb2.ListModelsRequest.FromString,
                    response_serializer=visionai_dot_infer_dot_v1_dot_infer__pb2.ListModelsResponse.SerializeToString,
            ),
            'LoadModel': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadModel,
                    request_deserializer=visionai_dot_infer_dot_v1_dot_infer__pb2.LoadModelRequest.FromString,
                    response_serializer=visionai_dot_infer_dot_v1_dot_infer__pb2.LoadModelResponse.SerializeToString,
            ),
            'UnloadModel': grpc.unary_unary_rpc_method_handler(
                    servicer.UnloadModel,
                    request_deserializer=visionai_dot_infer_dot_v1_dot_infer__pb2.UnloadModelRequest.FromString,
                    response_serializer=visionai_dot_infer_dot_v1_dot_infer__pb2.UnloadModelResponse.SerializeToString,
            ),
            'OpenSession': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenSession,
                    request_deserializer=visionai_dot_infer_dot_v1_dot_infer__pb2.OpenSessionRequest.FromString,
                    response_serializer=visionai_dot_infer_dot_v1_dot_infer__pb2.OpenSessionResponse.SerializeToString,
            ),
            'UpdateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSession,
                    request_deserializer=visionai_dot_infer_dot_v1_dot_infer__pb2.UpdateSessionRequest.FromString,
                    response_serializer=visionai_dot_infer_dot_v1_dot_infer__pb2.UpdateSessionResponse.SerializeToString,
            ),
            'CloseSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseSession,
                    request_deserializer=visionai_dot_infer_dot_v1_dot_infer__pb2.CloseSessionRequest.FromString,
                    response_serializer=visionai_dot_infer_dot_v1_dot_infer__pb2.CloseSessionResponse.SerializeToString,
            ),
            'Infer': grpc.unary_unary_rpc_method_handler(
                    servicer.Infer,
                    request_deserializer=visionai_dot_infer_dot_v1_dot_infer__pb2.InferRequest.FromString,
                    response_serializer=visionai_dot_infer_dot_v1_dot_infer__pb2.InferResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'visionai.infer.v1.InferService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('visionai.infer.v1.InferService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InferService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Live(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/visionai.infer.v1.InferService/Live',
            visionai_dot_infer_dot_v1_dot_infer__pb2.LiveRequest.SerializeToString,
            visionai_dot_infer_dot_v1_dot_infer__pb2.LiveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ready(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/visionai.infer.v1.InferService/Ready',
            visionai_dot_infer_dot_v1_dot_infer__pb2.ReadyRequest.SerializeToString,
            visionai_dot_infer_dot_v1_dot_infer__pb2.ReadyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/visionai.infer.v1.InferService/ListModels',
            visionai_dot_infer_dot_v1_dot_infer__pb2.ListModelsRequest.SerializeToString,
            visionai_dot_infer_dot_v1_dot_infer__pb2.ListModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/visionai.infer.v1.InferService/LoadModel',
            visionai_dot_infer_dot_v1_dot_infer__pb2.LoadModelRequest.SerializeToString,
            visionai_dot_infer_dot_v1_dot_infer__pb2.LoadModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnloadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/visionai.infer.v1.InferService/UnloadModel',
            visionai_dot_infer_dot_v1_dot_infer__pb2.UnloadModelRequest.SerializeToString,
            visionai_dot_infer_dot_v1_dot_infer__pb2.UnloadModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OpenSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/visionai.infer.v1.InferService/OpenSession',
            visionai_dot_infer_dot_v1_dot_infer__pb2.OpenSessionRequest.SerializeToString,
            visionai_dot_infer_dot_v1_dot_infer__pb2.OpenSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/visionai.infer.v1.InferService/UpdateSession',
            visionai_dot_infer_dot_v1_dot_infer__pb2.UpdateSessionRequest.SerializeToString,
            visionai_dot_infer_dot_v1_dot_infer__pb2.UpdateSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/visionai.infer.v1.InferService/CloseSession',
            visionai_dot_infer_dot_v1_dot_infer__pb2.CloseSessionRequest.SerializeToString,
            visionai_dot_infer_dot_v1_dot_infer__pb2.CloseSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Infer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/visionai.infer.v1.InferService/Infer',
            visionai_dot_infer_dot_v1_dot_infer__pb2.InferRequest.SerializeToString,
            visionai_dot_infer_dot_v1_dot_infer__pb2.InferResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
